### ISSUE TITLE
[INFO] acquire_data.py

### ISSUE THREAD

**Issue by CanisHelix** [Lanrek/hardpoint#1]
Hope you don't mind, I used this to download the data from myself quickly. I wanted all data, so I've modified the endpoints (also enabled CitizenCon ships myself)

It's mostly complete, added subTypes for duplicate names under ItemTypes. I didn't finish the merge block though but feel free to use the extra endpoints added here.

https://gist.github.com/ShiroiKuma/acfd723ed1be0b1f779528efb5379dbd

**Comment by Lanrek** [comment]
Glad you found it useful, although last I heard SCNIS is still a prototype that can't handle high load so please don't target any automation at it. :)

I've just switched this repository to doing direction data extraction rather than relying on SCNIS, though, so I won't be maintaining the old path.
